md "Todos os paises"
cd "Todos os paises"
md "Argentina"
md "Bolivia"
md "Brasil"
md "Chile"
md "Colombia"
md "Equador"
md "Guiana"
md "Paraguai"
md "Peru"
md "Suriname"
md "Uruguai"
md "Venezuela"
md "Guiana Francesa"

cd..
cd "Todos os paises"
cd "Brasil"
md "Acre (AC)"
md "Alagoas (AL)"
md "Amapa (AP)"
md "Amazonas (AM)"
md "Bahia (BA)"
md "Ceara (CE)"
md "Distrito Federal (DF)"
md "Espirito Santo (ES)"
md "Goias (GO)"
md "Maranhao (MA)"
md "Mato Grosso (MT)"
md "Mato Grosso do Sul (MS)"
md "Minas Gerais (MG)"
md "Para (PA)"
md "Paraiba (PB)"
md "Parana (PR)"
md "Pernambuco (PE)"
md "Piaui (PI)"
md "Rio de Janeiro (RJ)"
md "Rio Grande do Norte (RN)"
md "Rio Grande do Sul (RS)"
md "Rondonia (RO)"
md "Roraima (RR)"
md "Santa Catarina (SC)"
md "Sao Paulo (SP)"
md "Sergipe (SE)"
md "Tocantins (TO)"



