md "Todos os Estados"
cd "Todos os Estados"
md "Centro-Oeste"
md "Nordeste"
md "Norte"
md "Sul"
md "Sudeste"

cd "Centro-Oeste"
md "Mato Grosso (MT)"
md "Mato Grosso do Sul(MS)"
md "Goias (GO)"
md "Distrito Federal (DF)"
